export declare const FormActions: {
    readonly DEFAULT: "default";
    readonly BACK: "back-action";
    readonly PICK_AUTHENTICATOR: "pick-authenticator";
    readonly PICK_SMS: "pick-sms";
    readonly PICK_EMAIL: "pick-email";
    readonly PICK_COUNTRY_CODE: "pick-country-code";
    readonly RESEND_CODE: "resend-code";
    readonly RESEND: "resend";
    readonly CONTINUE: "continue";
    readonly TOGGLE_VIEW: "toggle-view";
    readonly ENTER_OTP_CODE: "enter-otp-code";
    readonly SWITCH_TO_VOICE: "switch-to-voice";
    readonly ABORT_PASSKEY_ENROLLMENT: "abort-passkey-enrollment";
    readonly BACK_TO_LOGIN: "back-to-login";
    readonly ACCEPT: "accept";
    readonly DENY: "deny";
    readonly ENROLL: "enroll";
    readonly RESEND_EMAIL: "resend-email-action";
    readonly PICK_PHONE: "pick-phone";
    readonly SWITCH_TO_SMS: "switch-to-sms";
    readonly CONFIRM: "confirm";
    readonly CANCEL: "cancel";
    readonly SHOW_ERROR_ACTION_PREFIX: "showError::";
    readonly SNOOZE_ENROLLMENT: "snooze-enrollment";
    readonly REFUSE_ADD_DEVICE: "refuse-add-device";
    readonly TRY_AGAIN: "tryagain";
    readonly USE_PASSWORD: "use-password";
};
//# sourceMappingURL=form-actions.d.ts.map